codecov:
  require_ci_to_pass: true

component_management:
  individual_components:
    - component_id: syn-cfg-attr
      name: "syn-cfg-attr"
      paths:
        - src/**

coverage:
  precision: 2
  round: down
  range: "90...100"
