name: update shared revisions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  update:
    uses: stayhydated/shared/.github/workflows/update-shared-revisions.yml@master
    with:
      app_client_id: ${{ vars.SHARED_REVISION_APP_CLIENT_ID }}
    secrets:
      app_private_key: ${{ secrets.SHARED_REVISION_APP_PRIVATE_KEY }}
