[application]
asset_dir = "public"
name = "syn-cfg-attr"
out_dir = "dist"

[web.app]
base_path = "syn-cfg-attr"
title = "syn-cfg-attr | Home"

[web.watcher]
index_on_404 = true
reload_html = true
watch_path = [ "src", "public" ]

[web.resource]
script = [  ]
style = [  ]

[web.resource.dev]
script = [  ]
style = [  ]
